######################################################################
# Automatically generated by qmake (3.0) Tue Nov 25 10:17:10 2014
######################################################################

TEMPLATE = app
TARGET = tdeck
INCLUDEPATH += .

# Input
HEADERS += cookiejar.h \
    myviewview.h \
    mywebpage.h
SOURCES += tdeck.cpp \
    myviewview.cpp \
    mywebpage.cpp
QT += widgets webkit webenginewidgets
ICON = tdeck.icns
