######################################################################
# Automatically generated by qmake (3.0) Tue Nov 25 10:17:10 2014
######################################################################

TEMPLATE = app
TARGET = tdeck
INCLUDEPATH += .

# Input
HEADERS += cookiejar.h
SOURCES += tdeck.cpp
QT += widgets webkit webkitwidgets
ICON = tdeck.icns
